version: '3.8'

services:
  frontend:
    build:
      context: ../shirt-store-frontend
    ports:
      - "4200:4200"
    volumes:
      - ../shirt-store-frontend:/app
    command: npm start

  backend:
    build:
      context: ../shirt-store-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shirt-store
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: miel123
      MYSQL_DATABASE: shirt-store
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - mysql-data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"  
    environment:
      PMA_HOST: mysql
      PMA_USER: root   
      PMA_PASSWORD: miel123 
      PMA_ARBITRARY: 1  
    depends_on:
      - mysql

volumes:
  mysql-data: