version: '3.8'

services:
  frontend:
    build:
      context: ../shirt-store-frontend
    ports:
      - "4200:4200"
    volumes:
      - ../shirt-store-frontend:/app
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - shirt-store-net

  backend:
    build:
      context: ../shirt-store-backend
    ports:
      - "8080:8080"
    networks:
      - shirt-store-net

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shirt-store
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass1234
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - shirt-store-net
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"  
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - shirt-store-net

volumes:
  mysql-data:

networks:
  shirt-store-net:
